/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/models/glb/bag.gltf");
    return (
        <group ref={group} {...props} dispose={null}>
            <group
                position={[0, -.005, 0]}
                rotation={[0, 0, 0]}
                scale={[1.06, 0.77, 0.96]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ATR001_Doypack_0.geometry}
                    material={materials.front}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ATR001_Doypack_0_1.geometry}
                    material={materials.back}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ATR001_Doypack_0_2.geometry}
                    material={materials.filler}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/glb/bag.gltf");